INSERT INTO Customer(company_name,fname,lname,username,pwd,email,phone_no) VALUES ('Microsoft','Robert','George','robg','pwd123','robg@gmail.com',91805532);
INSERT INTO Customer(company_name,fname,lname,username,pwd,email,phone_no) VALUES ('Kobenhavn Kommune','Stacy','Brown','sbrown','stacy12','stacy@gmail.com',91854332);
insert into Customer (company_name, fname, lname, username, pwd, email, phone_no) values ('Bubblemix', 'Jack', 'Frazier', 'jfrazier0', 'wVuIQqRs7', 'jfrazier0@t.co', '62-(373)521-9030');
insert into Customer (company_name, fname, lname, username, pwd, email, phone_no) values ('Topiczoom', 'Kenneth', 'Fernandez', 'kfernandez1', 'XcDzAnlTFkO', 'kfernandez1@sourceforge.net', '27-(105)655-7291');
insert into Customer (company_name, fname, lname, username, pwd, email, phone_no) values ('Brainverse', 'Keith', 'Lane', 'klane2', 'nSwuMTFUjZi', 'klane2@weather.com', '62-(122)309-0969');
insert into Customer (company_name, fname, lname, username, pwd, email, phone_no) values ('Meetz', 'Anthony', 'Allen', 'aallen3', 'vFUPcNHtPcb', 'aallen3@nba.com', '62-(715)675-0884');
insert into Customer (company_name, fname, lname, username, pwd, email, phone_no) values ('Voonder', 'Jennifer', 'Morris', 'jmorris4', 'XKMkXgpBZBt', 'jmorris4@mapy.cz', '7-(835)918-3014');
insert into Customer (company_name, fname, lname, username, pwd, email, phone_no) values ('Midel', 'Jean', 'Robertson', 'jrobertson5', '8PSeJP', 'jrobertson5@photobucket.com', '963-(336)554-2389');
insert into Customer (company_name, fname, lname, username, pwd, email, phone_no) values ('Innotype', 'Sharon', 'Ferguson', 'sferguson6', 'Xvu68a', 'sferguson6@list-manage.com', '86-(298)736-0967');
insert into Customer (company_name, fname, lname, username, pwd, email, phone_no) values ('Quatz', 'Joyce', 'Bradley', 'jbradley7', 'DTDq339MSesw', 'jbradley7@cyberchimps.com', '86-(300)539-0721');
insert into Customer (company_name, fname, lname, username, pwd, email, phone_no) values ('Photobean', 'David', 'Oliver', 'doliver8', 'YR0RcBA', 'doliver8@unesco.org', '234-(195)300-2239');
insert into Customer (company_name, fname, lname, username, pwd, email, phone_no) values ('Topicblab', 'Phillip', 'Williamson', 'pwilliamson9', '3iirY7By1gKh', 'pwilliamson9@163.com', '62-(890)577-6593');
insert into Customer (company_name, fname, lname, username, pwd, email, phone_no) values ('Agivu', 'Stephanie', 'Hart', 'sharta', 'EwHvG8y', 'sharta@nsw.gov.au', '86-(555)614-8260');
insert into Customer (company_name, fname, lname, username, pwd, email, phone_no) values ('Rhynoodle', 'Samuel', 'Mendoza', 'smendozab', 'M36Vqhx9l', 'smendozab@tmall.com', '595-(992)323-5739');
insert into Customer (company_name, fname, lname, username, pwd, email, phone_no) values ('Rhynoodle', 'Joshua', 'Ward', 'jwardc', 'j5UTCGpEFGj', 'jwardc@hp.com', '48-(372)132-8685');
insert into Customer (company_name, fname, lname, username, pwd, email, phone_no) values ('Bluezoom', 'Barbara', 'Dunn', 'bdunnd', 'KR8duHYPTm', 'bdunnd@usatoday.com', '1-(334)254-2749');
insert into Customer (company_name, fname, lname, username, pwd, email, phone_no) values ('Feedfish', 'Aaron', 'Black', 'ablacke', 'Ez8WIFsTK', 'ablacke@digg.com', '63-(169)858-5137');
insert into Customer (company_name, fname, lname, username, pwd, email, phone_no) values ('Topicblab', 'Bonnie', 'Lee', 'bleef', 'DMnlCGeG6lc', 'bleef@miitbeian.gov.cn', '62-(362)495-1718');
insert into Customer (company_name, fname, lname, username, pwd, email, phone_no) values ('Topiczoom', 'Steve', 'Nelson', 'snelsong', 'vOUlbNI', 'snelsong@auda.org.au', '86-(333)958-2237');
insert into Customer (company_name, fname, lname, username, pwd, email, phone_no) values ('Yambee', 'Gary', 'Spencer', 'gspencerh', 'PdnecgV', 'gspencerh@weather.com', '62-(565)314-0591');
insert into Customer (company_name, fname, lname, username, pwd, email, phone_no) values ('Kwimbee', 'Phyllis', 'Henry', 'phenryi', 'PP4P319', 'phenryi@taobao.com', '46-(233)281-9441');
insert into Customer (company_name, fname, lname, username, pwd, email, phone_no) values ('Browsedrive', 'James', 'Griffin', 'jgriffinj', 'bxNe8kTly5', 'jgriffinj@cbsnews.com', '51-(128)700-8860');
insert into Customer (company_name, fname, lname, username, pwd, email, phone_no) values ('Realbuzz', 'Wayne', 'Hamilton', 'whamiltonk', 'DQamSGqYKGoK', 'whamiltonk@ow.ly', '223-(209)538-4284');
insert into Customer (company_name, fname, lname, username, pwd, email, phone_no) values ('Skippad', 'Theresa', 'Baker', 'tbakerl', 'kARSfo', 'tbakerl@amazonaws.com', '380-(932)592-1798');
insert into Customer (company_name, fname, lname, username, pwd, email, phone_no) values ('Yozio', 'Dennis', 'Welch', 'dwelchm', 'ZQeINf12T9r', 'dwelchm@cnn.com', '965-(193)306-0448');
insert into Customer (company_name, fname, lname, username, pwd, email, phone_no) values ('Zoomdog', 'Mary', 'Reed', 'mreedn', 'DJQDSCdFjV', 'mreedn@bluehost.com', '234-(937)160-6674');
insert into Customer (company_name, fname, lname, username, pwd, email, phone_no) values ('Ainyx', 'Wayne', 'Payne', 'wpayneo', '1J9DCTYTuNT', 'wpayneo@123-reg.co.uk', '92-(344)782-0071');
insert into Customer (company_name, fname, lname, username, pwd, email, phone_no) values ('Muxo', 'Teresa', 'Griffin', 'tgriffinp', 'PJPO3H', 'tgriffinp@reuters.com', '86-(848)214-2956');
insert into Customer (company_name, fname, lname, username, pwd, email, phone_no) values ('Dynabox', 'Helen', 'Nguyen', 'hnguyenq', 'ZljRBBHYkxlL', 'hnguyenq@shutterfly.com', '62-(536)799-7428');
insert into Customer (company_name, fname, lname, username, pwd, email, phone_no) values ('Linkbridge', 'Marie', 'Morales', 'mmoralesr', 'Ta3NKR6', 'mmoralesr@springer.com', '1-(280)305-5939');
insert into Customer (company_name, fname, lname, username, pwd, email, phone_no) values ('Browsecat', 'Marilyn', 'Morrison', 'mmorrisons', 'SFVusg', 'mmorrisons@princeton.edu', '7-(599)307-5457');
insert into Customer (company_name, fname, lname, username, pwd, email, phone_no) values ('Bubbletube', 'Juan', 'Mills', 'jmillst', 'c8iq1TM', 'jmillst@chronoengine.com', '52-(195)715-4809');
insert into Customer (company_name, fname, lname, username, pwd, email, phone_no) values ('Gabvine', 'Christine', 'Mills', 'cmillsu', 'Egmvc3j', 'cmillsu@house.gov', '63-(932)717-6092');
insert into Customer (company_name, fname, lname, username, pwd, email, phone_no) values ('Omba', 'Phillip', 'Miller', 'pmillerv', 'KNcr4ivdQE86', 'pmillerv@upenn.edu', '62-(275)113-2891');
insert into Customer (company_name, fname, lname, username, pwd, email, phone_no) values ('Flipstorm', 'Bonnie', 'Campbell', 'bcampbellw', 'JXjc2RFM74', 'bcampbellw@acquirethisname.com', '355-(165)821-2787');
insert into Customer (company_name, fname, lname, username, pwd, email, phone_no) values ('Brainsphere', 'Dennis', 'Bryant', 'dbryantx', 'xOdfSfy6y', 'dbryantx@hatena.ne.jp', '1-(850)700-3014');
insert into Customer (company_name, fname, lname, username, pwd, email, phone_no) values ('Yakitri', 'Brian', 'Stone', 'bstoney', 'pZY9zOSvrM', 'bstoney@tinypic.com', '62-(142)466-5132');
insert into Customer (company_name, fname, lname, username, pwd, email, phone_no) values ('Quire', 'Judy', 'Harris', 'jharrisz', 'uwrlJPpO99', 'jharrisz@netvibes.com', '970-(463)205-5156');
insert into Customer (company_name, fname, lname, username, pwd, email, phone_no) values ('Kayveo', 'Judith', 'Baker', 'jbaker10', '1xWNnAQo8q5J', 'jbaker10@barnesandnoble.com', '62-(846)448-9799');
insert into Customer (company_name, fname, lname, username, pwd, email, phone_no) values ('Skivee', 'Gerald', 'Sanchez', 'gsanchez11', 'SGjE6B', 'gsanchez11@princeton.edu', '357-(697)424-4305');
insert into Customer (company_name, fname, lname, username, pwd, email, phone_no) values ('Oyope', 'Frank', 'Burke', 'fburke12', 'OBT2hnA', 'fburke12@flickr.com', '1-(622)525-1624');
insert into Customer (company_name, fname, lname, username, pwd, email, phone_no) values ('Aivee', 'Alice', 'Reid', 'areid13', 'WWEypib', 'areid13@facebook.com', '20-(299)650-2551');
insert into Customer (company_name, fname, lname, username, pwd, email, phone_no) values ('Topiclounge', 'Michelle', 'Fields', 'mfields14', 'E2A5360OCh', 'mfields14@clickbank.net', '86-(556)730-4423');
insert into Customer (company_name, fname, lname, username, pwd, email, phone_no) values ('Devify', 'Nicole', 'White', 'nwhite15', '8wqae0b', 'nwhite15@alexa.com', '7-(268)496-7327');
insert into Customer (company_name, fname, lname, username, pwd, email, phone_no) values ('Wordware', 'Christina', 'Palmer', 'cpalmer16', 'H5VAeeig', 'cpalmer16@hao123.com', '86-(681)317-6282');
insert into Customer (company_name, fname, lname, username, pwd, email, phone_no) values ('Buzzbean', 'Julia', 'Hamilton', 'jhamilton17', '3QAoO2FCL', 'jhamilton17@ycombinator.com', '46-(759)282-5223');
insert into Customer (company_name, fname, lname, username, pwd, email, phone_no) values ('Devbug', 'Kenneth', 'Thompson', 'kthompson18', 'dRsXJteTTe', 'kthompson18@time.com', '62-(672)434-1016');
insert into Customer (company_name, fname, lname, username, pwd, email, phone_no) values ('Yadel', 'Bobby', 'Olson', 'bolson19', 'hNCWSAV2L', 'bolson19@ebay.co.uk', '963-(734)705-9750');
insert into Customer (company_name, fname, lname, username, pwd, email, phone_no) values ('Wordware', 'Diana', 'Arnold', 'darnold1a', 'xLTc07Nia', 'darnold1a@wordpress.org', '55-(648)819-9170');
insert into Customer (company_name, fname, lname, username, pwd, email, phone_no) values ('Photojam', 'Jane', 'Perry', 'jperry1b', 'HzNNwiZV9JyH', 'jperry1b@latimes.com', '249-(304)425-6218');
insert into Customer (company_name, fname, lname, username, pwd, email, phone_no) values ('Dablist', 'Joan', 'Morris', 'jmorris1c', '22FItwS0WWux', 'jmorris1c@apple.com', '86-(186)559-9714');
insert into Customer (company_name, fname, lname, username, pwd, email, phone_no) values ('Jabberstorm', 'Thomas', 'Grant', 'tgrant1d', 'CGJi2IXqYADp', 'tgrant1d@bloglines.com', '86-(577)161-6140');
insert into Customer (company_name, fname, lname, username, pwd, email, phone_no) values ('Kanoodle', 'Sandra', 'Stanley', 'sstanley1e', 'AqI29pc', 'sstanley1e@bloglines.com', '1-(795)788-2256');
insert into Customer (company_name, fname, lname, username, pwd, email, phone_no) values ('Agivu', 'Virginia', 'Gilbert', 'vgilbert1f', 'ZSEo6I6MWbBE', 'vgilbert1f@dot.gov', '380-(629)312-3346');
insert into Customer (company_name, fname, lname, username, pwd, email, phone_no) values ('Eabox', 'Shawn', 'Jackson', 'sjackson1g', '7hREB8', 'sjackson1g@apple.com', '62-(365)437-4213');
insert into Customer (company_name, fname, lname, username, pwd, email, phone_no) values ('Dabshots', 'Diane', 'Sanchez', 'dsanchez1h', 'zIxv8BdX01', 'dsanchez1h@nydailynews.com', '86-(458)706-0435');
insert into Customer (company_name, fname, lname, username, pwd, email, phone_no) values ('Eare', 'Sean', 'Berry', 'sberry1i', 'Jq41JKU', 'sberry1i@yelp.com', '63-(250)599-0829');
insert into Customer (company_name, fname, lname, username, pwd, email, phone_no) values ('Realbridge', 'Angela', 'Gomez', 'agomez1j', 'wJ3Ily', 'agomez1j@washington.edu', '86-(300)670-8957');
insert into Customer (company_name, fname, lname, username, pwd, email, phone_no) values ('Youbridge', 'Ann', 'Welch', 'awelch1k', 'Z0AKmn0a3AS', 'awelch1k@google.de', '62-(253)767-0527');
insert into Customer (company_name, fname, lname, username, pwd, email, phone_no) values ('Gigazoom', 'Ashley', 'Gutierrez', 'agutierrez1l', 'Ib84wMr', 'agutierrez1l@sciencedirect.com', '62-(739)730-8871');
insert into Customer (company_name, fname, lname, username, pwd, email, phone_no) values ('Bluejam', 'Phyllis', 'Ray', 'pray1m', 'mC0bXxT', 'pray1m@mapquest.com', '351-(361)673-9195');
insert into Customer (company_name, fname, lname, username, pwd, email, phone_no) values ('Wikizz', 'Christine', 'Cooper', 'ccooper1n', 'DUo4fNFfGKal', 'ccooper1n@samsung.com', '971-(855)474-2470');
insert into Customer (company_name, fname, lname, username, pwd, email, phone_no) values ('Youtags', 'Phillip', 'Morris', 'pmorris1o', 'J9wB8ZatEk', 'pmorris1o@photobucket.com', '95-(506)219-8055');
insert into Customer (company_name, fname, lname, username, pwd, email, phone_no) values ('Plajo', 'Kevin', 'Lane', 'klane1p', 'uRk6j17f', 'klane1p@huffingtonpost.com', '7-(517)685-3773');
insert into Customer (company_name, fname, lname, username, pwd, email, phone_no) values ('Tavu', 'Michelle', 'Williams', 'mwilliams1q', 'JoKSbFr4Hhk0', 'mwilliams1q@naver.com', '86-(475)187-9272');
insert into Customer (company_name, fname, lname, username, pwd, email, phone_no) values ('Ainyx', 'Justin', 'Day', 'jday1r', 'FwlV0e6k', 'jday1r@over-blog.com', '62-(842)841-6798');
insert into Customer (company_name, fname, lname, username, pwd, email, phone_no) values ('Zava', 'Martin', 'Morris', 'mmorris1s', '1U1szXwQb', 'mmorris1s@wp.com', '1-(677)116-9071');
insert into Customer (company_name, fname, lname, username, pwd, email, phone_no) values ('Brainbox', 'Robin', 'Meyer', 'rmeyer1t', '77Qm1AcaDKH', 'rmeyer1t@multiply.com', '232-(533)137-6601');
insert into Customer (company_name, fname, lname, username, pwd, email, phone_no) values ('Geba', 'Jeffrey', 'Morgan', 'jmorgan1u', 'hVVRLsBmPmN', 'jmorgan1u@slashdot.org', '86-(103)280-1279');
insert into Customer (company_name, fname, lname, username, pwd, email, phone_no) values ('Edgeclub', 'Joe', 'Knight', 'jknight1v', '2XrWJkzk', 'jknight1v@ask.com', '420-(256)145-2486');
insert into Customer (company_name, fname, lname, username, pwd, email, phone_no) values ('Myworks', 'Douglas', 'Lopez', 'dlopez1w', 'OV8vm9', 'dlopez1w@dyndns.org', '218-(613)448-0352');
insert into Customer (company_name, fname, lname, username, pwd, email, phone_no) values ('Eare', 'Steven', 'Torres', 'storres1x', 'ISziAkFkVUl', 'storres1x@reverbnation.com', '86-(250)335-5412');
insert into Customer (company_name, fname, lname, username, pwd, email, phone_no) values ('Riffwire', 'Tina', 'Stewart', 'tstewart1y', 'K4q5IWxv69l', 'tstewart1y@go.com', '598-(689)275-4594');
insert into Customer (company_name, fname, lname, username, pwd, email, phone_no) values ('Einti', 'Dorothy', 'Pierce', 'dpierce1z', '2kCsHZevEkm', 'dpierce1z@mashable.com', '352-(156)384-1676');
insert into Customer (company_name, fname, lname, username, pwd, email, phone_no) values ('Teklist', 'Robert', 'Green', 'rgreen20', 'dBrXNiCw3THu', 'rgreen20@godaddy.com', '356-(628)865-0994');


INSERT INTO City VALUES(2800, 'Lyngby');
INSERT INTO City VALUES(2150, 'Nordhavn');
INSERT INTO City VALUES(2000, 'Frederiksberg');
INSERT INTO City VALUES(2100, 'Copenhagen O');
INSERT INTO City VALUES(2200, 'Copenhagen N');
INSERT INTO City VALUES(2300, 'Copenhagen S');
INSERT INTO City VALUES(2400, 'Copenhagen NV');
INSERT INTO City VALUES(2450, 'Copenhagen SV');
INSERT INTO City VALUES(2600, 'Glostrup');
INSERT INTO City VALUES(2605, 'Brondby');
INSERT INTO City VALUES(2610, 'Rodovre');
INSERT INTO City VALUES(2620, 'Albertslund');
INSERT INTO City VALUES(2625, 'Vallensbaek');
INSERT INTO City VALUES(2630, 'Taastrup');
INSERT INTO City VALUES(2635, 'Ishoj');
INSERT INTO City VALUES(2640, 'Hedehusene');
INSERT INTO City VALUES(2650, 'Hvidovre');
INSERT INTO City VALUES(2660, 'Brondby Strand');


INSERT INTO Services VALUES (11,'Leak detection');
INSERT INTO Services VALUES (12,'Moisture testing');
INSERT INTO Services VALUES (13,'Drying services');
INSERT INTO Services VALUES (14,'Grafiti removal');
INSERT INTO Services VALUES (15,'Burglary restoration');
INSERT INTO Services VALUES (16,'Fire damage');

INSERT INTO Building(street, zip, size, customer_id) VALUES('123 Fakestreet', 45692, 90, 1);
INSERT INTO Building(street, zip, size, customer_id) VALUES('546 Fakestreet', 45692, 90, 1);


INSERT INTO Employee(fname, lname, username, pwd, email, phone_no) VALUES ('Robert','Gosh','robgosh', 'pwd123','rg@sb.dk',12558312);
INSERT INTO Employee(fname, lname, username, pwd, email, phone_no) VALUES ('Mark','David','markdavid', 'pwd123','md@sb.dk',77558853);
INSERT INTO Employee(fname, lname, username, pwd, email, phone_no) VALUES ('Karl','Hasen','karlhasen', 'pwd123','kh@sb.dk',43558123);
INSERT INTO Employee(fname, lname, username, pwd, email, phone_no) VALUES ('Steward','Lane','stewlane', 'pwd123','sl@sb.dk',76848312);
INSERT INTO Employee(fname, lname, username, pwd, email, phone_no) VALUES ('Daniel','Plork','danielp', 'pwd123','dp@sb.dk',90978312);
INSERT INTO Employee(fname, lname, username, pwd, email, phone_no) VALUES ('John','Brown','johnbrown','pwd123','johnb@gmail.com',91007744);
INSERT INTO Employee(fname, lname, username, pwd, email, phone_no) VALUES ('Emily','Smith','esmith','password1','emily@gmail.com',010324578);
insert into Employee (fname, lname, username, pwd, email, phone_no) values ('Diana', 'Franklin', 'dfranklin0', '1TmdgquV', 'dfranklin0@japanpost.jp', '86-(256)871-6287');
insert into Employee (fname, lname, username, pwd, email, phone_no) values ('Wayne', 'Parker', 'wparker1', '0Ny1zFaIVLBv', 'wparker1@unc.edu', '33-(379)190-2436');
insert into Employee (fname, lname, username, pwd, email, phone_no) values ('Bruce', 'Harrison', 'bharrison2', 'wXl73kWbm8', 'bharrison2@dedecms.com', '86-(520)816-6041');
insert into Employee (fname, lname, username, pwd, email, phone_no) values ('Alice', 'Mitchell', 'amitchell3', 'VytR302', 'amitchell3@surveymonkey.com', '86-(689)223-7142');
insert into Employee (fname, lname, username, pwd, email, phone_no) values ('Victor', 'Bryant', 'vbryant4', 'IscPYOCtBC', 'vbryant4@cloudflare.com', '55-(261)599-2847');
insert into Employee (fname, lname, username, pwd, email, phone_no) values ('Adam', 'Lane', 'alane5', '2trGgLga', 'alane5@unc.edu', '387-(165)891-2646');


INSERT INTO Building (name,street,zip,parcel_no,size,condition_level,customer_id) VALUES ('Norre Flat', 'Norreport',1400,1500,344,0,1);
INSERT INTO Building (name,street,zip,parcel_no,size,condition_level,customer_id) VALUES ('Cozy Flats', 'Lyngbyvej 32',2800,1700,100,0,2);
insert into Building (name, street, zip, parcel_no, size, year, buildingUse, condition_level, customer_id) values ('Zoombeat', '552 High Crossing Circle', 2000, 970, 243, 1957, 'on', null, '58');
insert into Building (name, street, zip, parcel_no, size, year, buildingUse, condition_level, customer_id) values ('Linkbridge', '90410 Fuller Place', 2000, 901, 65, 1975, 'as', '3', '92');
insert into Building (name, street, zip, parcel_no, size, year, buildingUse, condition_level, customer_id) values ('Skyndu', '8 Ronald Regan Pass', 2000, 805, 386, 1982, 'be', '1', '22');
insert into Building (name, street, zip, parcel_no, size, year, buildingUse, condition_level, customer_id) values ('Reallinks', '59031 Hoffman Hill', 2000, 1952, 252, 1959, 'ms', '2', '05');
insert into Building (name, street, zip, parcel_no, size, year, buildingUse, condition_level, customer_id) values ('Rhyzio', '93 Nevada Road', 2000, 114, 12, 1994, 'an', '0', '38');
insert into Building (name, street, zip, parcel_no, size, year, buildingUse, condition_level, customer_id) values ('Meevee', '300 Portage Trail', 2000, 779, 139, 1970, 'OK', '3', '46');
insert into Building (name, street, zip, parcel_no, size, year, buildingUse, condition_level, customer_id) values ('Voomm', '11016 Lakeland Park', 2000, 182, 254, 1960, 'ad', '2', '89');
insert into Building (name, street, zip, parcel_no, size, year, buildingUse, condition_level, customer_id) values ('Twiyo', '673 Reinke Hill', 2000, 180, 85, 2007, 'ax', '2', '22');
insert into Building (name, street, zip, parcel_no, size, year, buildingUse, condition_level, customer_id) values ('Meembee', '29 Surrey Pass', 2000, 1855, 349, 1937, 'up', '3', '33');
insert into Building (name, street, zip, parcel_no, size, year, buildingUse, condition_level, customer_id) values ('Wikizz', '98519 Ronald Regan Circle', 2000, 1916, 315, 1947, 'as', null, '41');
insert into Building (name, street, zip, parcel_no, size, year, buildingUse, condition_level, customer_id) values ('Flashset', '2 Pawling Park', 2000, 1069, 109, 1993, 'Ms', '3', '61');
insert into Building (name, street, zip, parcel_no, size, year, buildingUse, condition_level, customer_id) values ('Bubbletube', '488 Village Green Avenue', 2000, 516, 184, 1920, 'if', '3', '82');
insert into Building (name, street, zip, parcel_no, size, year, buildingUse, condition_level, customer_id) values ('Zoomcast', '9452 Lukken Terrace', 2000, 1974, 309, 2013, 'ha', '1', '61');
insert into Building (name, street, zip, parcel_no, size, year, buildingUse, condition_level, customer_id) values ('Youspan', '0642 Huxley Avenue', 2000, 243, 283, 2013, 'if', '3', '35');
insert into Building (name, street, zip, parcel_no, size, year, buildingUse, condition_level, customer_id) values ('Brightbean', '98154 Riverside Crossing', 2000, 391, 362, 1962, 'ho', null, '67');
insert into Building (name, street, zip, parcel_no, size, year, buildingUse, condition_level, customer_id) values ('Yombu', '85720 Kim Way', 2000, 198, 78, 1983, 'ox', null, '44');
insert into Building (name, street, zip, parcel_no, size, year, buildingUse, condition_level, customer_id) values ('Realmix', '5 Dryden Crossing', 2000, 1064, 251, 2015, 'ms', '0', '05');
insert into Building (name, street, zip, parcel_no, size, year, buildingUse, condition_level, customer_id) values ('Tagopia', '3 Weeping Birch Drive', 2000, 1984, 161, 1925, 'ho', '3', '76');
insert into Building (name, street, zip, parcel_no, size, year, buildingUse, condition_level, customer_id) values ('Pixope', '8 Ridgeview Park', 2000, 1819, 59, 1954, 'em', '3', '11');
insert into Building (name, street, zip, parcel_no, size, year, buildingUse, condition_level, customer_id) values ('Voonix', '263 Summerview Street', 2000, 1089, 102, 1926, 'ay', '3', '12');
insert into Building (name, street, zip, parcel_no, size, year, buildingUse, condition_level, customer_id) values ('Skinte', '423 Eggendart Alley', 2000, 1352, 113, 2004, 'eh', null, '11');
insert into Building (name, street, zip, parcel_no, size, year, buildingUse, condition_level, customer_id) values ('Rhycero', '00 Maryland Crossing', 2000, 719, 20, 1946, 'Os', '2', '05');
insert into Building (name, street, zip, parcel_no, size, year, buildingUse, condition_level, customer_id) values ('Plajo', '214 Myrtle Place', 2000, 1570, 240, 1920, 'at', '0', '67');
insert into Building (name, street, zip, parcel_no, size, year, buildingUse, condition_level, customer_id) values ('Jaxworks', '92159 Schlimgen Lane', 2000, 166, 375, 1929, 'on', null, '82');
insert into Building (name, street, zip, parcel_no, size, year, buildingUse, condition_level, customer_id) values ('Einti', '14 Springs Crossing', 2000, 545, 329, 2009, 'to', '0', '10');
insert into Building (name, street, zip, parcel_no, size, year, buildingUse, condition_level, customer_id) values ('Twitterlist', '22 Anhalt Terrace', 2000, 1549, 227, 1933, 'an', '3', '07');
insert into Building (name, street, zip, parcel_no, size, year, buildingUse, condition_level, customer_id) values ('Gigabox', '25 Westport Terrace', 2000, 429, 28, 1978, 'Os', '2', '52');
insert into Building (name, street, zip, parcel_no, size, year, buildingUse, condition_level, customer_id) values ('Divanoodle', '085 Melody Point', 2000, 1157, 57, 1995, 'in', '2', '56');
insert into Building (name, street, zip, parcel_no, size, year, buildingUse, condition_level, customer_id) values ('Skinder', '50 School Pass', 2000, 1530, 174, 2012, 'go', '3', '80');
insert into Building (name, street, zip, parcel_no, size, year, buildingUse, condition_level, customer_id) values ('Skajo', '1221 Sunnyside Junction', 2000, 1145, 210, 1994, 'do', '2', '48');
insert into Building (name, street, zip, parcel_no, size, year, buildingUse, condition_level, customer_id) values ('Edgewire', '8 Mallard Crossing', 2000, 606, 367, 1922, 'us', null, '39');
insert into Building (name, street, zip, parcel_no, size, year, buildingUse, condition_level, customer_id) values ('Fadeo', '47472 6th Alley', 2000, 1381, 225, 1962, 'of', null, '96');
insert into Building (name, street, zip, parcel_no, size, year, buildingUse, condition_level, customer_id) values ('DabZ', '9 Union Crossing', 2000, 610, 322, 1935, 'ah', '3', '24');
insert into Building (name, street, zip, parcel_no, size, year, buildingUse, condition_level, customer_id) values ('Devbug', '444 Lakeland Street', 2000, 868, 86, 1997, 'am', '3', '78');
insert into Building (name, street, zip, parcel_no, size, year, buildingUse, condition_level, customer_id) values ('Oyondu', '89759 Mosinee Circle', 2000, 241, 298, 1988, 'Ms', '0', '56');
insert into Building (name, street, zip, parcel_no, size, year, buildingUse, condition_level, customer_id) values ('Cogibox', '7204 Morning Circle', 2000, 210, 50, 1957, 'it', '3', '29');
insert into Building (name, street, zip, parcel_no, size, year, buildingUse, condition_level, customer_id) values ('Topiczoom', '695 Bultman Way', 2000, 1627, 334, 1939, 'my', '3', '76');
insert into Building (name, street, zip, parcel_no, size, year, buildingUse, condition_level, customer_id) values ('Trilia', '7 Loomis Street', 2000, 454, 371, 1926, 'id', '1', '62');
insert into Building (name, street, zip, parcel_no, size, year, buildingUse, condition_level, customer_id) values ('Roombo', '12 Mendota Circle', 2000, 1353, 231, 1941, 'on', '2', '18');
insert into Building (name, street, zip, parcel_no, size, year, buildingUse, condition_level, customer_id) values ('Realbridge', '35565 Mesta Drive', 2000, 1861, 154, 1937, 'no', '3', '82');
insert into Building (name, street, zip, parcel_no, size, year, buildingUse, condition_level, customer_id) values ('Youtags', '26 Tony Point', 2000, 55, 400, 1990, 'is', '3', '47');
insert into Building (name, street, zip, parcel_no, size, year, buildingUse, condition_level, customer_id) values ('Oyoyo', '748 Pearson Crossing', 2000, 1648, 294, 2013, 'Mr', null, '43');
insert into Building (name, street, zip, parcel_no, size, year, buildingUse, condition_level, customer_id) values ('Meejo', '9375 Pepper Wood Lane', 2000, 804, 32, 2014, 'it', null, '69');
insert into Building (name, street, zip, parcel_no, size, year, buildingUse, condition_level, customer_id) values ('Edgetag', '65 Ryan Lane', 2000, 1304, 379, 1939, 'OK', '3', '28');
insert into Building (name, street, zip, parcel_no, size, year, buildingUse, condition_level, customer_id) values ('Babbleblab', '5052 Mccormick Circle', 2000, 867, 272, 1977, 're', '1', '84');
insert into Building (name, street, zip, parcel_no, size, year, buildingUse, condition_level, customer_id) values ('Topicware', '81699 Merchant Point', 2000, 1927, 257, 1934, 'on', null, '38');
insert into Building (name, street, zip, parcel_no, size, year, buildingUse, condition_level, customer_id) values ('Gabspot', '302 Morning Avenue', 2000, 374, 358, 2008, 'id', null, '73');
insert into Building (name, street, zip, parcel_no, size, year, buildingUse, condition_level, customer_id) values ('Topiclounge', '00 Brickson Park Circle', 2000, 1153, 66, 1964, 'up', '0', '57');
insert into Building (name, street, zip, parcel_no, size, year, buildingUse, condition_level, customer_id) values ('Bluezoom', '0237 New Castle Street', 2000, 1365, 151, 1991, 'or', '2', '87');
insert into Building (name, street, zip, parcel_no, size, year, buildingUse, condition_level, customer_id) values ('Skiba', '53607 Donald Parkway', 2000, 1013, 210, 2014, 'or', '1', '42');
insert into Building (name, street, zip, parcel_no, size, year, buildingUse, condition_level, customer_id) values ('Dazzlesphere', '7094 Boyd Crossing', 2000, 941, 166, 2011, 'an', '3', '34');
insert into Building (name, street, zip, parcel_no, size, year, buildingUse, condition_level, customer_id) values ('Oyonder', '7 Dakota Court', 2000, 438, 36, 1980, 'up', '3', '07');
insert into Building (name, street, zip, parcel_no, size, year, buildingUse, condition_level, customer_id) values ('Devify', '3760 Lukken Hill', 2000, 1836, 136, 1982, 'oh', '0', '87');
insert into Building (name, street, zip, parcel_no, size, year, buildingUse, condition_level, customer_id) values ('Thoughtbridge', '7384 Magdeline Alley', 2000, 265, 253, 1928, 'ho', '2', '76');
insert into Building (name, street, zip, parcel_no, size, year, buildingUse, condition_level, customer_id) values ('Kazio', '4477 Fuller Drive', 2000, 767, 224, 1963, 'is', null, '24');
insert into Building (name, street, zip, parcel_no, size, year, buildingUse, condition_level, customer_id) values ('Trudoo', '6151 Kennedy Terrace', 2000, 927, 244, 1963, 'ho', '2', '32');
insert into Building (name, street, zip, parcel_no, size, year, buildingUse, condition_level, customer_id) values ('Ainyx', '1442 Lakeland Park', 2000, 626, 310, 1984, 're', '3', '77');
insert into Building (name, street, zip, parcel_no, size, year, buildingUse, condition_level, customer_id) values ('Browsetype', '0 Service Road', 2000, 870, 130, 1970, 'id', '0', '20');
insert into Building (name, street, zip, parcel_no, size, year, buildingUse, condition_level, customer_id) values ('Quire', '99749 Randy Terrace', 2000, 1962, 304, 1936, 'hi', '0', '05');
insert into Building (name, street, zip, parcel_no, size, year, buildingUse, condition_level, customer_id) values ('Voolith', '466 Old Gate Junction', 2000, 1403, 90, 1993, 'at', '1', '16');
insert into Building (name, street, zip, parcel_no, size, year, buildingUse, condition_level, customer_id) values ('Katz', '48758 Commercial Avenue', 2000, 97, 43, 1972, 'ma', '2', '14');
insert into Building (name, street, zip, parcel_no, size, year, buildingUse, condition_level, customer_id) values ('Skajo', '8374 Schlimgen Street', 2000, 335, 212, 1985, 'id', null, '16');
insert into Building (name, street, zip, parcel_no, size, year, buildingUse, condition_level, customer_id) values ('Chatterbridge', '81675 Dwight Crossing', 2000, 1720, 328, 1966, 'ma', '3', '38');
insert into Building (name, street, zip, parcel_no, size, year, buildingUse, condition_level, customer_id) values ('Dabshots', '9244 Spenser Place', 2000, 1021, 124, 1929, 'in', '3', '48');
insert into Building (name, street, zip, parcel_no, size, year, buildingUse, condition_level, customer_id) values ('BlogXS', '88 Melby Plaza', 2000, 398, 277, 1968, 'id', '2', '21');
insert into Building (name, street, zip, parcel_no, size, year, buildingUse, condition_level, customer_id) values ('Twitterwire', '667 Eagle Crest Way', 2000, 1586, 108, 1988, 'cs', '3', '77');
insert into Building (name, street, zip, parcel_no, size, year, buildingUse, condition_level, customer_id) values ('Babblestorm', '3982 Alpine Point', 2000, 1041, 65, 2008, 'he', null, '94');
insert into Building (name, street, zip, parcel_no, size, year, buildingUse, condition_level, customer_id) values ('Browseblab', '44421 Michigan Point', 2000, 982, 255, 1991, 'in', null, '86');
insert into Building (name, street, zip, parcel_no, size, year, buildingUse, condition_level, customer_id) values ('Vipe', '23 Buell Trail', 2000, 1002, 271, 1972, 'be', '3', '11');
insert into Building (name, street, zip, parcel_no, size, year, buildingUse, condition_level, customer_id) values ('Blogtags', '50 Esch Lane', 2000, 297, 124, 1995, 'Es', '2', '31');
insert into Building (name, street, zip, parcel_no, size, year, buildingUse, condition_level, customer_id) values ('Avamm', '18 Hooker Court', 2000, 1747, 22, 1939, 'it', '3', '20');
insert into Building (name, street, zip, parcel_no, size, year, buildingUse, condition_level, customer_id) values ('Buzzbean', '4532 Dapin Avenue', 2000, 686, 61, 1955, 'by', '1', '74');
insert into Building (name, street, zip, parcel_no, size, year, buildingUse, condition_level, customer_id) values ('Eimbee', '0 Chinook Plaza', 2000, 1175, 204, 2001, 'ha', '3', '74');
insert into Building (name, street, zip, parcel_no, size, year, buildingUse, condition_level, customer_id) values ('Gabspot', '1921 Elgar Terrace', 2000, 708, 235, 1942, 'if', '2', '15');
insert into Building (name, street, zip, parcel_no, size, year, buildingUse, condition_level, customer_id) values ('Divavu', '56 Dahle Park', 2000, 1535, 221, 1963, 'ox', '3', '84');
insert into Building (name, street, zip, parcel_no, size, year, buildingUse, condition_level, customer_id) values ('Plambee', '54408 Carpenter Way', 2000, 433, 145, 1999, 'mu', null, '75');
insert into Building (name, street, zip, parcel_no, size, year, buildingUse, condition_level, customer_id) values ('Plajo', '52391 West Trail', 2000, 1558, 364, 1991, 'go', '3', '47');
insert into Building (name, street, zip, parcel_no, size, year, buildingUse, condition_level, customer_id) values ('Oodoo', '4511 Drewry Alley', 2000, 1827, 165, 1985, 'oh', null, '81');
insert into Building (name, street, zip, parcel_no, size, year, buildingUse, condition_level, customer_id) values ('Wikizz', '1 Continental Alley', 2000, 1432, 325, 1986, 'on', '3', '40');
insert into Building (name, street, zip, parcel_no, size, year, buildingUse, condition_level, customer_id) values ('Wikibox', '81 Scott Street', 2000, 995, 125, 2009, 'he', '2', '36');
insert into Building (name, street, zip, parcel_no, size, year, buildingUse, condition_level, customer_id) values ('Yoveo', '757 Petterle Terrace', 2000, 647, 147, 2016, 'ma', '0', '64');
insert into Building (name, street, zip, parcel_no, size, year, buildingUse, condition_level, customer_id) values ('Tambee', '127 Forster Place', 2000, 1487, 387, 1981, 'so', '0', '1');
insert into Building (name, street, zip, parcel_no, size, year, buildingUse, condition_level, customer_id) values ('Topdrive', '5525 Derek Terrace', 2000, 1539, 299, 1981, 'Os', null, '17');
insert into Building (name, street, zip, parcel_no, size, year, buildingUse, condition_level, customer_id) values ('Flashset', '425 Atwood Place', 2000, 9, 142, 1939, 'ox', '3', '43');
insert into Building (name, street, zip, parcel_no, size, year, buildingUse, condition_level, customer_id) values ('Skimia', '01 Spaight Street', 2000, 1898, 195, 1931, 'of', '2', '80');
insert into Building (name, street, zip, parcel_no, size, year, buildingUse, condition_level, customer_id) values ('Yoveo', '1410 Logan Avenue', 2000, 1459, 74, 2005, 'do', null, '16');
insert into Building (name, street, zip, parcel_no, size, year, buildingUse, condition_level, customer_id) values ('Yambee', '93041 Del Mar Hill', 2000, 600, 373, 1975, 'be', '3', '43');
insert into Building (name, street, zip, parcel_no, size, year, buildingUse, condition_level, customer_id) values ('Devcast', '49775 Ohio Crossing', 2000, 48, 368, 2002, 'in', '1', '55');
insert into Building (name, street, zip, parcel_no, size, year, buildingUse, condition_level, customer_id) values ('Eazzy', '26 Corry Crossing', 2000, 844, 291, 1938, 'go', '3', '85');
insert into Building (name, street, zip, parcel_no, size, year, buildingUse, condition_level, customer_id) values ('Jaxnation', '5 Walton Junction', 2000, 1321, 248, 1948, 'if', '2', '76');
insert into Building (name, street, zip, parcel_no, size, year, buildingUse, condition_level, customer_id) values ('Roodel', '8010 Main Crossing', 2000, 79, 95, 1985, 'ho', null, '69');
insert into Building (name, street, zip, parcel_no, size, year, buildingUse, condition_level, customer_id) values ('Eire', '6 Clarendon Crossing', 2000, 1009, 263, 1983, 'we', '3', '71');
insert into Building (name, street, zip, parcel_no, size, year, buildingUse, condition_level, customer_id) values ('Dabfeed', '815 Reindahl Street', 2000, 1018, 170, 1977, 'pi', '3', '99');
insert into Building (name, street, zip, parcel_no, size, year, buildingUse, condition_level, customer_id) values ('Voonder', '63805 High Crossing Trail', 2000, 1796, 314, 1924, 'us', '3', '63');
insert into Building (name, street, zip, parcel_no, size, year, buildingUse, condition_level, customer_id) values ('Skyvu', '79 Sherman Parkway', 2000, 922, 145, 1934, 'no', '2', '50');
insert into Building (name, street, zip, parcel_no, size, year, buildingUse, condition_level, customer_id) values ('Feedfire', '8431 Onsgard Plaza', 2000, 1069, 292, 1973, 'or', null, '05');
insert into Building (name, street, zip, parcel_no, size, year, buildingUse, condition_level, customer_id) values ('Gabspot', '311 Scofield Park', 2000, 1036, 166, 1931, 'it', '0', '58');
insert into Building (name, street, zip, parcel_no, size, year, buildingUse, condition_level, customer_id) values ('Oyoloo', '2 Moose Street', 2000, 1550, 158, 1966, 'ms', '3', '49');
insert into Building (name, street, zip, parcel_no, size, year, buildingUse, condition_level, customer_id) values ('Rhyloo', '78 Oak Avenue', 2000, 1428, 32, 1977, 'on', '2', '60');
insert into Building (name, street, zip, parcel_no, size, year, buildingUse, condition_level, customer_id) values ('Babbleopia', '274 Nancy Way', 2000, 1621, 81, 1997, 'ad', '3', '10');
